---
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-22.04
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint -c config/yamllint/.yamllint .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build sonar jacocoTestReport --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}